services:
  postgres:
    image: postgres:18
    network_mode: bridge
    container_name: postgres
    restart: unless-stopped
    shm_size: 128mb
    # volumes:
    #   - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5001:5432"
